name: ncckios
description: App bán vé cho kios của NCC

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^5.5.0
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  flutter_bloc: ^6.0.1
  shared_preferences: ^0.5.8
  json_serializable: ^3.3.0
  google_fonts: ^1.1.0
  flutter_svg: ^0.18.0
  carousel_slider: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
